# Nombre de la aplicación
spring.application.name=sorteo-alumnos

# Configuración de la Base de Datos (Usa variables de Render o valores por defecto para tu PC)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/alumnos_bd?serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# Driver y Dialecto
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Importante: Como ya subiste las tablas a Aiven, ponlo en 'none' para que Spring no las toque
spring.jpa.hibernate.ddl-auto=none

# Configuración de errores y logs
server.error.include-message=always
spring.jpa.show-sql=true

# Puerto del servidor (Render lo manejará internamente, pero 8080 es el estándar)
server.port=8080
